build:
  container_name: nodejsSample_build
  image: miiixr/picklete_env
  extends:
    file: ./dockerConfig/development.yml
    service: build

  working_dir: /nodejsSample
  volumes:
    - ./:/nodejsSample

test:
  container_name: nodejsSample_test
  image: miiixr/picklete_env
  extends:
    file: ./dockerConfig/development.yml
    service: test

  external_links:
    - mysql

  working_dir: /picklete
  volumes:
    - ./:/picklete

web:
  container_name: nodejsSample
  image: miiixr/picklete_env
  extends:
    file: ./dockerConfig/development.yml
    service: web

  external_links:
    - mysql

  working_dir: /nodejsSample
  volumes:
    - ./:/nodejsSample

  restart: always


mysql:
  container_name: mysql
  image: dgraziotin/mysql
  extends:
    file: ./dockerConfig/development.yml
    service: mysql
  volumes:
    - ../database:/var/lib/mysql/

  restart: always
